[project]
name = "wandering-waterfall-e545"
version = "0.1.0"
description = "Text to Image Generator API with FastAPI and HTML rendering"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "playwright>=1.40.0",
]

[dependency-groups]
dev = [
    "workers-py",
 "uvicorn",
]
